apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tempurl-httproute.fullname" . }}-script
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tempurl-httproute.labels" . | nindent 4 }}
data:
  refresh.py: |
    {{- .Files.Get "files/refresh.py" | nindent 4 }}
