{{- if .Values.keys }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tempurl-httproute.keySecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tempurl-httproute.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.keys }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
